Table wmo_codes {
  id INTEGER [PRIMARY KEY, increment]
  code SMALLINT [NOT NULL, UNIQUE]
  description VARCHAR(40) [NOT NULL]
  created_at TIMESTAMP [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`]
  updated_at TIMESTAMP [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`]
}

Table weather_units {
  id INTEGER [PRIMARY KEY, increment]
  unit_type VARCHAR(16) [NOT NULL]
  unit_code VARCHAR(4) [NOT NULL]
  unit VARCHAR(10) [NOT NULL]
  created_at TIMESTAMP [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`]
  updated_at TIMESTAMP [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`]
}

Table current_weathers {
  id INTEGER [PRIMARY KEY, increment]
  uuid VARCHAR(32) [NOT NULL]
  location_name VARCHAR(64) [NOT NULL]
  location_country VARCHAR(64) [NOT NULL]
  location_latitude NUMERIC(11,8) [NOT NULL]
  location_longitude NUMERIC(11,8) [NOT NULL]
  data_latitude NUMERIC(11,8) [NOT NULL]
  data_longitude NUMERIC(11,8) [NOT NULL]
  distance_km REAL [NOT NULL]
  distance_mi REAL [NOT NULL]
  timezone VARCHAR(32) [NOT NULL]
  timezone_short VARCHAR(16) [NOT NULL]
  utc_offset_seconds INTEGER [NOT NULL]
  elevation REAL [NOT NULL]
  temperature_c REAL [NOT NULL]
  temperature_f REAL [NOT NULL]
  windspeed_kmh REAL [NOT NULL]
  windspeed_ms REAL [NOT NULL]
  windspeed_mph REAL [NOT NULL]
  windspeed_kn REAL [NOT NULL]
  winddirection REAL [NOT NULL]
  weathercode SMALLINT [NOT NULL]
  is_day boolean [NOT NULL]
  data_timestamp TIMESTAMP [NOT NULL]
  data_timestamp_utc TIMESTAMP [NOT NULL]
  created_at TIMESTAMP [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`]
  updated_at TIMESTAMP [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`]
}

Table weather_forecasts {
  id INTEGER [PRIMARY KEY, increment]
  uuid VARCHAR(32) [NOT NULL]
  location_name VARCHAR(64) [NOT NULL]
  location_country VARCHAR(64) [NOT NULL]
  location_latitude NUMERIC(11,8) [NOT NULL]
  location_longitude NUMERIC(11,8) [NOT NULL]
  data_latitude NUMERIC(11,8) [NOT NULL]
  data_longitude NUMERIC(11,8) [NOT NULL]
  distance_km REAL [NOT NULL]
  distance_mi REAL [NOT NULL]
  timezone VARCHAR(32) [NOT NULL]
  timezone_short VARCHAR(16) [NOT NULL]
  utc_offset_seconds INTEGER [NOT NULL]
  elevation REAL [NOT NULL]
  temperature_2m_c REAL [NOT NULL]
  temperature_2m_f REAL [NOT NULL]
  apparent_temperature_c REAL [NOT NULL]
  apparent_temperature_f REAL [NOT NULL]
  windspeed_10m_kmh REAL [NOT NULL]
  windspeed_10m_ms REAL [NOT NULL]
  windspeed_10m_mph REAL [NOT NULL]
  windspeed_10m_kn REAL [NOT NULL]
  winddirection_10m REAL [NOT NULL]
  relativehumidity_2m REAL [NOT NULL]
  precipitation_probability REAL [NOT NULL]
  precipitation_mm REAL [NOT NULL]
  precipitation_in REAL [NOT NULL]
  weathercode SMALLINT [NOT NULL]
  forecast_timestamp TIMESTAMP [NOT NULL]
  forecast_timestamp_utc TIMESTAMP [NOT NULL]
  is_day boolean [NOT NULL]
  data_timestamp TIMESTAMP [NOT NULL]
  data_timestamp_utc TIMESTAMP [NOT NULL]
  created_at TIMESTAMP [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`]
  updated_at TIMESTAMP [NOT NULL, DEFAULT: `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'`]
}

