/** Denormalized database for quick reporting
    For use in PostgreSQL DB server
 **/

CREATE TABLE "wmo_codes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" SMALLINT UNIQUE NOT NULL,
  "description" VARCHAR(40) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
  "updated_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE "weather_units" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_type" VARCHAR(16) NOT NULL,
  "unit_code" VARCHAR(4) NOT NULL,
  "unit" VARCHAR(10) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
  "updated_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE "current_weathers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" VARCHAR(32) NOT NULL,
  "location_name" VARCHAR(64) NOT NULL,
  "location_country" VARCHAR(64) NOT NULL,
  "location_latitude" NUMERIC(11,8) NOT NULL,
  "location_longitude" NUMERIC(11,8) NOT NULL,
  "data_latitude" NUMERIC(11,8) NOT NULL,
  "data_longitude" NUMERIC(11,8) NOT NULL,
  "distance" REAL NOT NULL,
  "utc_offset_seconds" INTEGER NOT NULL,
  "timezone" VARCHAR(32) NOT NULL,
  "timezone_short" VARCHAR(16) NOT NULL,
  "elevation" REAL NOT NULL,
  "data_timestamp" TIMESTAMP NOT NULL,
  "data_timestamp_utc" TIMESTAMP NOT NULL,
  "temperature_c" REAL NOT NULL,
  "temperature_f" REAL NOT NULL,
  "windspeed_kmh" REAL NOT NULL,
  "windspeed_ms" REAL NOT NULL,
  "windspeed_mph" REAL NOT NULL,
  "windspeed_kn" REAL NOT NULL,
  "winddirection" REAL NOT NULL,
  "winddirection_unit" VARCHAR(4) NOT NULL,
  "is_day" boolean NOT NULL,
  "weathercode" SMALLINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
  "updated_at" TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

ALTER TABLE "current_weathers" ADD FOREIGN KEY ("weathercode") REFERENCES "wmo_codes" ("code");

